[package]
name = "L432Test"
version = "0.0.0"
edition = "2018"

[build]
target = "thumbv7em-none-eabihf"

[dependencies]
stm32l4 = { version = "0.14.0",  features = ["stm32l4x2", "rt"] }
cortex-m = "0.7.3"
cortex-m-rt = "0.6.15"
cortex-m-semihosting = "0.3.7"
panic-semihosting = "0.5.6"
